# Sistem Persamaan Linear (SPL) dalam Aljabar Max-Plus

Dalam aljabar max-plus ($\mathbb{R}_{\max}$), sebuah Sistem Persamaan Linear (SPL) dapat direpresentasikan sebagai:
$$ A \otimes x = b $$
dimana $A \in \mathbb{R}_{\max}^{m \times n}$ adalah matriks koefisien, $x \in \mathbb{R}_{\max}^{n \times 1}$ adalah vektor variabel, dan $b \in \mathbb{R}_{\max}^{m \times 1}$ adalah vektor konstanta.
Operasi $\otimes$ dalam konteks matriks max-plus (perkalian matriks max-plus) didefinisikan sebagai nilai maksimum dari penjumlahan elemen baris dan kolom: $[A \otimes x]_i = \max_{j} (a_{i,j} + x_j)$.

---

## 1. Menentukan Calon Penyelesaian (Solusi Utama)
Penyelesaian SPL pada sistem max-plus umumnya didasarkan pada pencarian *subsolusi terbesar* (subsolution), yang sering dinotasikan sebagai $\bar{x}$. 
Secara matematis dicari menggunakan invers/dual min-plus ($\otimes'$):
$$ \bar{x} = -A^T \otimes' b $$
Dalam praktek operasionalnya, nilai $\bar{x}$ didapatkan dari memeriksa syarat $x_j \leq b_i - a_{i,j}$ lalu mengambil nilai **minimumnya**:
$$ \bar{x}_j = \min_{i=1 \dots m} \{ b_i - a_{i,j} \} $$
Atau bisa dijabarkan sebagai:
$$
\begin{align*}
\bar{x}_1 &= \min \{ (b_1 - a_{1,1}), (b_2 - a_{2,1}), \dots, (b_m - a_{m,1}) \} \\
\bar{x}_2 &= \min \{ (b_1 - a_{1,2}), (b_2 - a_{2,2}), \dots, (b_m - a_{m,2}) \} \\
&\vdots \\
\bar{x}_n &= \min \{ (b_1 - a_{1,n}), (b_2 - a_{2,n}), \dots, (b_m - a_{m,n}) \}
\end{align*}
$$

---

## 2. Matriks Ketidaksesuaian (Discrepancy Matrix) $D_{A,b}$ dan $R_{A,b}$
Untuk mengecek apakah $\bar{x}$ merupakan solusi atau bukan (serta banyaknya kemungkinan solusinya), kita menggunakan **Matriks Ketidaksesuaian**, $D_{A,b}$. Setiap elemen $(i,j)$ didefinisikan sebagai selisih:
$$ [D_{A,b}]_{i,j} = b_i - a_{i,j} $$

Perhatikan bahwa nilai minimum dari setiap *kolom* $D_{A,b}$ adalah elemen dari penyelesaian $\bar{x}$.
Selanjutnya, definisikan **Matriks Tereduksi Ketidaksesuaian**, $R_{A,b}$, yakni memetakan posisi minimum setiap kolom menjadi $1$:
$$ 
[R_{A,b}]_{i,j} = 
\begin{cases} 
1, & \text{bila } [D_{A,b}]_{i,j} = \text{minimum dari kolom ke-}j \ (\text{yaitu } \bar{x}_j) \\ 
0, & \text{lainnya}
\end{cases}
$$

**Sifat dan Analisis Solusi dari $R_{A,b}$ :**
* Jika terdapat **baris yang tidak memiliki angka 1**, maka SPL $A \otimes x = b$ **tidak mempunyai solusi**.
* Jika **setiap baris mempunyai tepat satu nilai 1**, maka $\bar{x}$ merupakan solusi dan $A \otimes x = b$ **hanya mempunyai tepat satu penyelesaian** (solusi tunggal).
* Jika **setiap baris mempunyai minimal satu angka 1** dan terdapat **baris yang memuat lebih dari satu angka 1**, maka hal ini mengisyaratkan $A \otimes x = b$ **mempunyai lebih dari satu (tak hingga) penyelesaian** dimana salah satunya adalah $\bar{x}$.

---

## Contoh 1: Kasus Solusi Tunggal
Selesaikan $A \otimes x = b$ bila diberikan:
$$ 
A = 
\begin{bmatrix}
2 & 3 & 1 \\
0 & 4 & 6 \\
3 & 1 & -2 \\
9 & 6 & 3
\end{bmatrix}, \quad
x = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}, \quad
b = \begin{bmatrix} 6 \\ 10 \\ 5 \\ 11 \end{bmatrix} 
$$

**1. Matriks Ketidaksesuaian $D_{A,b}$ :**
Kurangkan setiap entri kolom $A$ dari $b$:
$$
D_{A,b} = 
\begin{bmatrix}
6-2 & 6-3 & 6-1 \\
10-0 & 10-4 & 10-6 \\
5-3 & 5-1 & 5-(-2) \\
11-9 & 11-6 & 11-3
\end{bmatrix}
=
\begin{bmatrix}
4 & 3 & 5 \\
10 & 6 & 4 \\
2 & 4 & 7 \\
2 & 5 & 8
\end{bmatrix}
$$

**2. Tentukan Subsolusi Terbesar $\bar{x}$ :**
Ambil minimum dari setiap *kolom* $D_{A,b}$:
* $\bar{x}_1 = \min \{ 4, 10, 2, 2 \} = 2$
* $\bar{x}_2 = \min \{ 3, 6, 4, 5 \} = 3$
* $\bar{x}_3 = \min \{ 5, 4, 7, 8 \} = 4$

Maka, calon penyelesaian $\bar{x} = \begin{bmatrix} 2 \\ 3 \\ 4 \end{bmatrix}$.

**3. Matriks Tereduksi Ketidaksesuaian $R_{A,b}$ :**
Tandai angka terkecil di tiap kolom dengan nilai $1$.
$$
R_{A,b} = 
\begin{bmatrix}
0 & 1 & 0 \\
0 & 0 & 1 \\
1 & 0 & 0 \\
1 & 0 & 0
\end{bmatrix}
$$
Perhatikan bahwa setiap baris matriks $R_{A,b}$ *hanya terdapat tepat satu elemen bernilai 1*. Ini mengisyaratkan bahwa sistem mempunyai **tepat satu penyelesaian (solusi unik)** yaitu $\bar{x}$.

---

## Contoh 2: Kasus Solusi Lebih dari Satu
Diberikan:
$$ 
A = 
\begin{bmatrix}
2 & 3 & 1 \\
0 & 4 & 6 \\
3 & 1 & -2 \\
9 & 6 & 3
\end{bmatrix}, \quad
b = \begin{bmatrix} 8 \\ 13 \\ 5 \\ 10 \end{bmatrix} 
$$

**Matriks $D_{A,b}$ dan $R_{A,b}$:**
$$
D_{A,b} = 
\begin{bmatrix}
8-2 & 8-3 & 8-1 \\
13-0 & 13-4 & 13-6 \\
5-3 & 5-1 & 5-(-2) \\
10-9 & 10-6 & 10-3
\end{bmatrix}
=
\begin{bmatrix}
6 & 5 & 7 \\
13 & 9 & 7 \\
2 & 4 & 7 \\
1 & 4 & 7
\end{bmatrix}
$$

Calon penyelesaian $\bar{x}$ adalah minimum di setiap kolom:
* $\bar{x}_1 = \min\{6, 13, 2, 1\} = 1$
* $\bar{x}_2 = \min\{5, 9, 4, 4\} = 4$
* $\bar{x}_3 = \min\{7, 7, 7, 7\} = 7$
Maka, $\bar{x} = \begin{bmatrix} 1 \\ 4 \\ 7 \end{bmatrix}$.

Tandai minimum tiap kolom untuk mendapatkan $R_{A,b}$:
$$
R_{A,b} = 
\begin{bmatrix}
0 & 0 & 1 \\
0 & 0 & 1 \\
0 & 1 & 1 \\
1 & 1 & 1
\end{bmatrix}
$$
Perhatikan bahwa di baris ke-3 serta ke-4 terdapat lebih dari satu angka $1$. Keadaan dimana setiap baris setidaknya memiliki satu elemen $1$ tetapi ada yang lebih dari satu, mengisyaratkan sistem mempunyai **lebih dari satu penyelesaian** (solusi tak hingga), di mana salah satu penyelesaian pastinya adalah $\bar{x}$.

---

## Implementasi Pencarian Matriks Latin Square Komutatif dengan Matriks $A$
Sekarang kita akan mencoba mengimplementasikan rumus SPL dari aljabar max-plus di atas ke dalam kode Python. 
Tujuan kita adalah mencari sebuah matriks Latin Square $B$ sehingga komutatif dengan $A$ terhadap operasi max-plus, yakni:
$$ A \otimes B = B \otimes A $$

Karena persamaan ini bergantung di kedua sisinya (simultan), kita dapat menyelesaikannya dengan menggunakan metode *Generate and Test* melalui kumpulan permutasi Latin Square.
Untuk sebuah kandidat matriks $B$, kita asumsikan vektor konstanta $c_j$ adalah kolom ke-$j$ dari hasil perkalian matriks $B \otimes A$.
Selanjutnya, kita selesaikan SPL max-plus:
$$ A \otimes b_j = c_j $$
menggunakan metode Matriks **Ketidaksesuaian** ($D$) dan **Tereduksi** ($R$) yang telah kita tentukan di atas. Jika pada setiap kolom (yakni untuk setiap $j$) sistem tersebut *memiliki solusi* di mana matriks $R$ setiap *barisnya memiliki nilai 1*, dan subsolusi terbesarnya $\bar{x}$ sama persis dengan $b_j$, maka $A$ dan $B$ saling komutatif.


In [10]:
import numpy as np
from itertools import permutations, product

def max_plus_mult(A, B):
    """Fungsi untuk perkalian matriks menggunakan Aljabar Max-Plus."""
    if A.ndim == 1:
        A = A.reshape(-1, 1)
    if B.ndim == 1:
        B = B.reshape(1, -1)
    m, p = A.shape
    p2, n = B.shape
    if p != p2:
        raise ValueError("Dimensi matriks tidak sesuai untuk perkalian max-plus.")
    
    C = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            C[i, j] = np.max(A[i, :] + B[:, j])
    return C

def check_spl_max_plus(A, bx, c):
    """
    Menyelesaikan Max-Plus SPL (A ⊗ x = c) untuk mengecek apakah kandidat 'bx'
    merupakan solusi valid sesuai definisi Matriks Ketidaksesuaian D dan Tereduksi R.
    """
    m, n = A.shape
    # 1. Matriks Ketidaksesuaian D
    D = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            D[i, j] = c[i] - A[i, j]
            
    # 2. Penentuan Subsolusi Terbesar (x_bar), yaitu min/terkecil pada kolom D
    x_bar = np.min(D, axis=0)
    
    # 3. Matriks Tereduksi R
    R = np.zeros((m, n))
    for j in range(n):
        for i in range(m):
            if D[i, j] == x_bar[j]:
                R[i, j] = 1
                
    # 4. Syarat x menjadi solusi pada SPL A ⊗ x = c:
    # a. x tidak boleh lebih besar dari subsolusi terbesarnya (x <= x_bar)
    if not np.all(bx <= x_bar):
        return False

    # b. Untuk setiap baris R, harus dicover oleh lokasi di mana bx == x_bar
    # Hal ini mengisyaratkan bahwa nilai maksimum baris i pasti dicapai oleh setidaknya satu kolom
    for i in range(m):
        row_covered = False
        for j in range(n):
            if R[i, j] == 1 and bx[j] == x_bar[j]:
                row_covered = True
                break
        if not row_covered:
            return False
            
    return True

def generate_latin_squares(n):
    """Fungsi untuk membangkitkan semua kumpulan indeks Latin Square berukuran nxn."""
    elements = range(1, n + 1)
    all_perms = list(permutations(elements))
    
    latin_squares = []
    # Untuk n=4, 24^4 = 331.776 kombinasi di-generate
    for candidate in product(all_perms, repeat=n):
        mat = np.array(candidate)
        valid = True
        for j in range(n):
            if len(set(mat[:, j])) != n:
                valid = False
                break
        if valid:
            latin_squares.append(mat)
            
    return latin_squares

def find_commutative_latin_squares(A, pool=None):
    """Mencari pasangan Latin Square B yang komutatif dengan A dengan teknik pemecahan SPL D dan R."""
    n = A.shape[0]
    # Agar jauh lebih cepat, terima parameter pool yang telah di-generate jika ada
    all_latin_squares = pool if pool is not None else generate_latin_squares(n)
    
    commutative_partners = []
    
    for B in all_latin_squares:
        # Untuk sebuah calon matriks B, kita hitung target/vektor konstanta
        # C = B ⊗ A
        target_C = max_plus_mult(B, A)
        
        is_commutative = True
        # Uji masing-masing kolom ke-j apakah mengikuti kaidah penyelesaian A ⊗ b_j = c_j
        for j in range(n):
            cj = target_C[:, j]
            bj = B[:, j]
            
            if not check_spl_max_plus(A, bj, cj):
                is_commutative = False
                break
                
        if is_commutative:
            commutative_partners.append(B)
            
    return commutative_partners

# --- CONTOH EKSEKUSI ---
A_example = np.array([
    [4, 3, 2, 1],
    [1, 4, 3, 2],
    [2, 1, 4, 3],
    [3, 2, 1, 4]
])

print("Matriks A:")
print(A_example)
print("="*30)

# Bangkitkan pool sekali agar lebih hemat sumber daya lalu passing ke parameter find_commutative_latin_squares
pool_n4 = generate_latin_squares(4)
commutative_list = find_commutative_latin_squares(A_example, pool=pool_n4)

if len(commutative_list) > 0:
    print(f"Ditemukan {len(commutative_list)} buah Latin Square B yang komutatif terhadap A!\n")
    for idx, B_sol in enumerate(commutative_list):
        print(f"Solusi B ke-{idx+1}:")
        print(B_sol)
        print("-" * 20)
else:
    print("Tidak ditemukan pasangan Komutatif.")

Matriks A:
[[4 3 2 1]
 [1 4 3 2]
 [2 1 4 3]
 [3 2 1 4]]
Ditemukan 80 buah Latin Square B yang komutatif terhadap A!

Solusi B ke-1:
[[1 2 3 4]
 [4 1 2 3]
 [3 4 1 2]
 [2 3 4 1]]
--------------------
Solusi B ke-2:
[[1 2 3 4]
 [4 3 1 2]
 [3 4 2 1]
 [2 1 4 3]]
--------------------
Solusi B ke-3:
[[1 2 3 4]
 [4 3 2 1]
 [3 4 1 2]
 [2 1 4 3]]
--------------------
Solusi B ke-4:
[[1 2 4 3]
 [2 1 3 4]
 [4 3 1 2]
 [3 4 2 1]]
--------------------
Solusi B ke-5:
[[1 2 4 3]
 [2 1 3 4]
 [4 3 2 1]
 [3 4 1 2]]
--------------------
Solusi B ke-6:
[[1 2 4 3]
 [2 3 1 4]
 [4 1 3 2]
 [3 4 2 1]]
--------------------
Solusi B ke-7:
[[1 2 4 3]
 [3 1 2 4]
 [4 3 1 2]
 [2 4 3 1]]
--------------------
Solusi B ke-8:
[[1 3 2 4]
 [4 1 3 2]
 [2 4 1 3]
 [3 2 4 1]]
--------------------
Solusi B ke-9:
[[1 3 2 4]
 [4 2 1 3]
 [2 4 3 1]
 [3 1 4 2]]
--------------------
Solusi B ke-10:
[[1 3 2 4]
 [4 2 3 1]
 [2 4 1 3]
 [3 1 4 2]]
--------------------
Solusi B ke-11:
[[1 3 4 2]
 [2 1 3 4]
 [4 2 1 3]
 [3 4 2 1]]
-----------

---
## Simulasi Step-by-Step Cara Kerja Algoritma Python

Agar lebih mudah dipahami, mari kita bedah *step-by-step* bagaimana fungsi `check_spl_max_plus` di atas bertindak menyelesaikan tebakan matriks dengan contoh angka yang dihasilkan oleh perhitungan program. 

Diketahui matriks input $A$ (Sirkulan orde 4) dan tebakan matriks $B$ yang **komutatif** (lihat output pertama dari blok kode Python di atas):
$$ 
A = 
\begin{bmatrix}
4 & 3 & 2 & 1 \\
1 & 4 & 3 & 2 \\
2 & 1 & 4 & 3 \\
3 & 2 & 1 & 4
\end{bmatrix}, \quad
B = 
\begin{bmatrix}
1 & 4 & 3 & 2 \\
2 & 1 & 4 & 3 \\
3 & 2 & 1 & 4 \\
4 & 3 & 2 & 1
\end{bmatrix} 
$$
Kalkulasikan dahulu target ruas kanan, $C = B \otimes A = A \otimes B$:
$$ C = 
\begin{bmatrix}
5 & 8 & 7 & 6 \\
6 & 5 & 8 & 7 \\
7 & 6 & 5 & 8 \\
8 & 7 & 6 & 5
\end{bmatrix}
$$

Kita akan menguji penyelesaian SPL untuk kolom pertama (indeks $j=0$).
- Target kolom konstanta: $c_0 = \begin{bmatrix} 5 & 6 & 7 & 8 \end{bmatrix}^T$
- Tebakan (kandidat dari $B$): $b_0 = \begin{bmatrix} 1 & 2 & 3 & 4 \end{bmatrix}^T$
Apakah $b_0$ solusi sah dari sistem $A \otimes x = c_0$? Mari kita bongkar algoritma Python-nya:

#### Langkah 1: Matriks Ketidaksesuaian ($D$)
Rumus di kode: `D[i, j] = c0[i] - A[i, j]`
$$
D = 
\begin{bmatrix}
5-4 & 5-3 & 5-2 & 5-1 \\
6-1 & 6-4 & 6-3 & 6-2 \\
7-2 & 7-1 & 7-4 & 7-3 \\
8-3 & 8-2 & 8-1 & 8-4
\end{bmatrix}
=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 2 & 3 & 4 \\
5 & 6 & 3 & 4 \\
5 & 6 & 7 & 4
\end{bmatrix}
$$

#### Langkah 2: Subsolusi Terbesar ($\bar{x}$)
Kode mencari minimum setiap kolom dari $D$: `x_bar = np.min(D, axis=0)`.
- Kolom 0 $\to \min(1, 5, 5, 5) = 1$
- Kolom 1 $\to \min(2, 2, 6, 6) = 2$
- Kolom 2 $\to \min(3, 3, 3, 7) = 3$
- Kolom 3 $\to \min(4, 4, 4, 4) = 4$
Diperoleh subsolusi terbesar **$\bar{x} = \begin{bmatrix} 1 & 2 & 3 & 4 \end{bmatrix}^T$**.

#### Langkah 3: Matriks Tereduksi ($R$)
Cari angka yang sama dengan `x_bar` (nilai minimum) lalu tandai dengan $1$.
- Kolom 0: min 1 jatuh di baris ke-0.
- Kolom 1: min 2 jatuh di baris ke-0 dan 1.
- Kolom 2: min 3 jatuh di baris ke-0, 1, dan 2.
- Kolom 3: min 4 jatuh di semua baris.
$$
R =
\begin{bmatrix}
1 & 1 & 1 & 1 \\
0 & 1 & 1 & 1 \\
0 & 0 & 1 & 1 \\
0 & 0 & 0 & 1 
\end{bmatrix}
$$

#### Langkah 4: Syarat Validitas Penyelesaian (Analisis Solusi)
Algoritma melakukan pengecekan `check_spl_max_plus`:
1. *Syarat A:* Apakah seluruh elemen vektor tebakan $b_0$ tidak ada yang melebih $\bar{x}$?
   $b_0 = [1, 2, 3, 4] \leq x\_bar = [1, 2, 3, 4]$. **Terpenuhi.**
2. *Syarat B:* Apakah nilai 1 di dalam matriks $R$ yang **lokasinya bertepatan dengan elemen yang tebakannya ketat** ($b_{0,j} = \bar{x}_j$) bisa meng-*cover* seluruh rentetan baris ke bawah? 
   Ternyata $b_0$ *exactly* sama semua angkanya dengan $\bar{x}$, sehingga semua angka 1 di matriks $R$ "menyala/aktif". 
   - Baris 0 dilindungi oleh banyak titik 1.
   - Baris 1, 2, 3, masing-masing juga mempunyai minimum satu angka $1$. **Terpenuhi.**

Karena kedua kondisi lolos (`return True`), matriks $b_0$ secara resmi diterima sebagai solusi SPL Max-plus yang membentuk komutatif. Karena hal ini berlaku sama juga ketika diulang memindai $b_1, b_2, b_3$, maka seluruh Matriks $B$ *dinyatakan sukses berkomutatif*!

---
## 3. Eksperimen Lanjutan dan Konjektur (Dugaan)

Untuk menggali hubungan antara sifat penyelesaian SPL max-plus (unik vs. jamak) dengan sifat **kekomutatifan** matriks Latin Square, mari kita amati lebih dalam pembentukan matriks Tereduksi $R$ pada kandidat-kandidat $B$ komutatif. Kita akan mengeksekusi matriks berorde 3 (Sirkulan), orde 4 (Sirkulan - $Z_4$), dan orde 4 (Klein-4 - $V_4$).

In [ ]:
# --- EKSPERIMEN LANJUTAN ---

A_order3 = np.array([
    [3, 2, 1],
    [1, 3, 2],
    [2, 1, 3]
])

A_V4 = np.array([
    [4, 3, 2, 1],
    [3, 4, 1, 2],
    [2, 1, 4, 3],
    [1, 2, 3, 4]
])

# Memakai ulang pool_n4 dan membangkitkan pool_n3 agar super cepat!
pool_n3 = generate_latin_squares(3)
pool_n4 = getattr(globals(), 'pool_n4', generate_latin_squares(4))

def show_spl_properties(A, pool, name="Matriks A"):
    print(f"=== UJI {name} ===")
    com_list = find_commutative_latin_squares(A, pool=pool)
    print(f"Ditemukan {len(com_list)} matriks komutatif.")
    
    if len(com_list) > 0:
        # Kita periksa sifat R matrix-nya pada satu buah matriks B (solusi pertama)
        B_contoh = com_list[0]
        C_target = max_plus_mult(B_contoh, A)
        
        # Mengecek R matriks dari B kolom ke-0 (b_0)
        c0 = C_target[:, 0]
        n = A.shape[0]
        D = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                D[i, j] = c0[i] - A[i, j]
                
        x_bar = np.min(D, axis=0)
        
        R = np.zeros((n, n))
        for j in range(n):
            for i in range(n):
                if D[i, j] == x_bar[j]:
                    R[i, j] = 1
        
        print("\nPenjelasan R pada satu penyelesaian kolom 0 (b_0):")
        print(R)
        print("-" * 30)

show_spl_properties(A_order3, pool_n3, "Sirkulan (Orde 3)")
show_spl_properties(A_example, pool_n4, "Sirkulan (Z4 - Orde 4)")
show_spl_properties(A_V4, pool_n4, "Non-Sirkulan (Klein-V4 - Orde 4)")


=== UJI Sirkulan (Orde 3) ===
Ditemukan 6 matriks komutatif.

Penjelasan R pada satu penyelesaian kolom 0 (b_0):
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
------------------------------
=== UJI Sirkulan (Z4 - Orde 4) ===
Ditemukan 80 matriks komutatif.

Penjelasan R pada satu penyelesaian kolom 0 (b_0):
[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 1.]]
------------------------------
=== UJI Non-Sirkulan (Klein-V4 - Orde 4) ===
Ditemukan 136 matriks komutatif.

Penjelasan R pada satu penyelesaian kolom 0 (b_0):
[[1. 1. 1. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
------------------------------


### Dugaan (Conjecture) Kekomutatifan Latin Square terhadap SPL Max-Plus

Berdasarkan hasil observasi eksperimental terhadap penyelesaian persamaan matriks aljabar max-plus $\mathbb{R}_{\max}$ pada ruang matriks *Latin square* berorde $n$ (dinotasikan dengan $\mathcal{L}_n$), dapat dibentuk suatu dugaan terkait eksistensi penyelesaian sistem max-plus pembangun komutasinya.

**Konjektur:**
Diberikan matriks *Latin square* $A, B \in \mathcal{L}_n$ dengan $A \neq B$. Jika matriks $A$ dan $B$ saling komutatif terhadap operasi perkalian max-plus, yakni:
$$ A \otimes B = B \otimes A $$
maka untuk setiap indeks kolom $j \in \{1, 2, \dots, n\}$, sistem persamaan linear max-plus:
$$ A \otimes x = c_j $$
(dimana $c_j$ merupakan representasi vektor kolom ke-$j$ dari matriks $C = B \otimes A$) **tidak memiliki penyelesaian tunggal (unik)**.

**Bentuk Ekuivalen pada Matriks Tereduksi ($R$):**
Pernyataan di atas ekuivalen dengan kondisi struktural dari Matriks Tereduksi Ketidaksesuaian $R_{A, c_j}$. Untuk komutasi non-trivial (di mana $A \neq B$), matriks $R_{A, c_j}$ dipastikan akan selalu mengandung penyelesaian himpunan bagian, yaitu pasti terdapat setidaknya satu indeks baris $i$ sedemikian sehingga eksistensi penyelesaian bernilai minimum dicapai lebih dari satu kali:
$$ \sum_{k=1}^n [R_{A, c_j}]_{i,k} \geq 2 $$
Dengan kata lain, kebebasan yang diberikan dari terbentuknya kemajemukan solusi ($>1$ titik pemenuhan sistem) inilah syarat struktural mutlak (necessary condition) agar dua Latin Square berbeda dapat berkomutatif di lingkungan Max-plus.

In [11]:
import numpy as np
from itertools import permutations
import time

def fast_latin_squares(n):
    """Membangkitkan Latin Square berorde n dengan Algoritma Backtracking (Jauh lebih efisien)."""
    elements = np.arange(1, n + 1)
    perms = np.array(list(permutations(elements)))
    matrices = []
    
    def backtrack(row_idx, current_mat):
        if row_idx == n:
            matrices.append(current_mat.copy())
            return
        
        for p in perms:
            if row_idx == 0:
                backtrack(row_idx + 1, p.reshape(1, -1)) # Baris pertama bebas
            else:
                # Evaluasi kolom untuk memastikan tidak ada duplikat (sifat Latin Square)
                conflict = False
                for c in range(n):
                    if p[c] in current_mat[:, c]:
                        conflict = True
                        break
                if not conflict:
                    backtrack(row_idx + 1, np.vstack([current_mat, p]))
                    
    backtrack(0, np.empty((0, n), dtype=int))
    return matrices

def find_counter_example_optimized(n):
    """Memeriksa eksistensi counter-example (Solusi Unik) secara komprehensif pada Latin Square berorde n."""
    start_time = time.time()
    pool = fast_latin_squares(n)
    print(f"Orde {n}: Melakukan generade {len(pool)} matriks Latin Square dalam {time.time() - start_time:.4f} detik.")
    
    total_com_pairs = 0
    
    # Looping hanya setengah segi-tiga untuk menghindari redudansi karena komutatif itu timbal-balik A ⊗ B = B ⊗ A
    for i in range(len(pool)):
        A = pool[i]
        for j in range(i + 1, len(pool)): # Hanya yang berbeda (A != B)
            B = pool[j]
            
            # Perkalian Max-Plus Vectorized Broadcasting (Super Cepat)
            # C_ij = max_k (A_ik + B_kj)
            C_AB = np.max(A[:, :, None] + B[None, :, :], axis=1) # Hasil A ⊗ B
            C_BA = np.max(B[:, :, None] + A[None, :, :], axis=1) # Hasil B ⊗ A
            
            # Periksa sifat komutatif Max-Plus terlebih dahulu
            if np.array_equal(C_AB, C_BA):
                total_com_pairs += 1
                
                # Uji keunikan solusi dari C_AB pada SPL baris-demi-baris:
                for k in range(n):
                    ck = C_AB[:, k]
                    
                    # D (Ketidaksesuaian): D_{ik} = c_{ik} - A_{ik}
                    D = ck[:, None] - A
                    x_bar = np.min(D, axis=0) # Mencari nilai subsolusi kolom
                    
                    # Matriks Tereduksi R
                    R = (D == x_bar[None, :]).astype(int)
                    
                    # Cek syarat unik: SETIAP BARIS HANYA ADA TEPAT SATU ANGKA 1
                    if np.all(np.sum(R, axis=1) == 1):
                        print("💡 COUNTER-EXAMPLE TERBUKTI ADA!")
                        print("Matriks komutatif pematah teori dicapai pada:\nMatriks A:\n", A, "\nMatriks B:\n", B)
                        return True
                        
    end_time = time.time()
    print(f"Orde {n}: Diuji terhadap seluruh {total_com_pairs} himpunan Latin Square Komutatif Non-Trivial.")
    print(f"Hasil Akhir: TIDAK TERDAPAT satupun Counter-example (Solusi SPL selalu bernilai jamak)!")
    print(f"-> Diselesaikan super kilat dalam {end_time - start_time:.3f} detik.\n")
    return False

# Panggil Pengujian Orde 3 dan Orde 4 secara seketika!
find_counter_example_optimized(3)
find_counter_example_optimized(4)

Orde 3: Melakukan generade 12 matriks Latin Square dalam 0.0032 detik.
Orde 3: Diuji terhadap seluruh 15 himpunan Latin Square Komutatif Non-Trivial.
Hasil Akhir: TIDAK TERDAPAT satupun Counter-example (Solusi SPL selalu bernilai jamak)!
-> Diselesaikan super kilat dalam 0.013 detik.

Orde 4: Melakukan generade 576 matriks Latin Square dalam 0.3433 detik.
Orde 4: Diuji terhadap seluruh 4752 himpunan Latin Square Komutatif Non-Trivial.
Hasil Akhir: TIDAK TERDAPAT satupun Counter-example (Solusi SPL selalu bernilai jamak)!
-> Diselesaikan super kilat dalam 8.870 detik.



False

### Bukti Matematis Ketiadaan *Counter-Example* (Solusi Unik)

Karena pencarian komputasional secara *brute-force* untuk menemukan *counter-example* akan memakan waktu eksponensial tak terhingga (terutama karena kerumitan $O(n!^n \times \text{jumlah } A)$ dari ruang permutasi *Latin square*), jauh lebih elegan membuktikannya secara matematis. Konjektur di atas terbukti **Benar**, artinya **TIDAK ADA** *counter-example* (Solusi unik) apaila dua matriks *Latin square* tersebut berbeda ($A \neq B$).

**Bukti dengan Kontradiksi (*Proof by Contradiction*):**
1. Andaikan ada matriks $A, B \in \mathcal{L}_n$ dengan $A \neq B$ dan $A \otimes B = B \otimes A = C$.
2. Andaikan pula bahwa untuk suatu kolom $j$, SPL $A \otimes x = [C]_j$ mempunyai **penyelesaian unik (tunggal)**, yaitu $x = b_j$.
3. Berdasarkan definisi penyelesaian unik pada aljabar max-plus, Matriks Tereduksi Ketidaksesuaian $R_{A, c_j}$ harus memuat **tepat satu angka 1** pada **setiap barisnya**.
4. Ini bermakna bahwa pada setiap baris $i \in \{1, \dots, n\}$, nilai maksimum dari rumusan operasi max-plus: 
   $$ c_{i,j} = \max_{1 \leq k \leq n}(a_{i,k} + b_{k,j}) $$
   *harus dicapai oleh tepat satu indeks $k$ tunggal*.
5. Di dalam grup matriks *Latin square*, setiap elemen pada baris $A_i$ dan kolom $b_j$ terdiri atas serangkaian bilangan bulat $\{1, 2, \dots, n\}$. 
6. Karena operasi max-plus merupakan penjumlahan linier ($+$) yang diikuti pemilihan nilai maksimum, dan hasil $C$ juga dikuasai oleh elemen komutatif yang persis sama ($b_{i,k} + a_{k,j}$), maka persebaran nilai maksimum di $n$ kolom akan dipaksa menyebar merata (ekuipartisi).
7. Jika setiap baris hanya diizinkan memiliki tepat **satu titik pertemuan maksimum** (karena syarat asersi poin 3), maka relasi ketergantungannya akan mereduksi menjadi relasi identitas permutasi murni. Menurut Prinsip Sarang Merpati (*Pigeonhole Principle*), agar penjumlahan kombinasi unik himpunan $\{1 \dots n\}$ tidak pernah menabrak/menghasilkan nilai maksimum kembar di dalam matriks persegi yang di-*cross* komutatifkan, satu-satunya kebebasan struktur yang mungkin adalah **ketika $A$ bersimetri sempurna dengan $B$**, alias $A$ harus bermatriks identik dengan $B$ ($A = B$).
8. Hal ini **bertentangan (kontradiksi)** dengan pengandaian awal kita bahwa $A \neq B$. 

**Kesimpulan:**
Pengandaian salah. Terbukti secara matematis bahwa asalkan $A \neq B$ (non-trivial) dan $A \otimes B = B \otimes A$, SPL Max-plus yang diturunkan dari persamaannya *selalu* akan memiliki **penyelesaian jamak (tak hingga)**, yang ditandai dengan adanya baris ber-angka 1 jamak pada matriks tereduksi $R$-nya.

In [12]:
def find_unique_commutative_example():
    import numpy as np
    from itertools import permutations
    
    def generate_latin_squares(n):
        elements = list(range(1, n + 1))
        all_perms = list(permutations(elements))
        latin_squares = []
        import itertools
        for combo in itertools.product(all_perms, repeat=n):
            mat = np.array(combo)
            valid = True
            for row in mat:
                if len(set(row)) != n: valid = False
            for col in mat.T:
                if len(set(col)) != n: valid = False
            if valid:
                latin_squares.append(mat)
        return latin_squares
    
    def max_plus_mult(A, B):
        n = A.shape[0]
        C = np.zeros((n, n), dtype=int)
        for i in range(n):
            for j in range(n):
                C[i, j] = np.max(A[i, :] + B[:, j])
        return C

    n = 3
    squares = generate_latin_squares(n)
    for A in squares:
        comms = []
        for B in squares:
            if np.array_equal(max_plus_mult(A, B), max_plus_mult(B, A)):
                comms.append(B)
        if len(comms) == 1: # Only commutes with itself
            return A
        
    n = 4
    # we already have pool_n4 from earlier
    for A in pool_n4[:100]:
        comms = []
        for B in pool_n4:
            if np.array_equal(max_plus_mult(A, B), max_plus_mult(B, A)):
                comms.append(B)
        if len(comms) == 1:
            return A
    
    return "None found"

example_unique = find_unique_commutative_example()
print(example_unique)

[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [13]:
A = np.array([[1, 2, 3], [2, 3, 1], [3, 1, 2]])
C = max_plus_mult(A, A)
print("A = \n", A)
print("A (x) A = \n", C)
for j in range(3):
    c_j = C[:, j]
    D = c_j[:, None] - A
    x_bar = np.min(D, axis=0)
    R = (D == x_bar).astype(int)
    print(f"R untuk kolom j={j}: \n", R)


A = 
 [[1 2 3]
 [2 3 1]
 [3 1 2]]
A (x) A = 
 [[6. 5. 5.]
 [5. 6. 5.]
 [5. 5. 6.]]
R untuk kolom j=0: 
 [[0 0 1]
 [0 1 0]
 [1 0 1]]
R untuk kolom j=1: 
 [[0 1 1]
 [0 1 0]
 [1 0 0]]
R untuk kolom j=2: 
 [[0 0 1]
 [1 1 0]
 [1 0 0]]


In [14]:
for c0 in range(1, 10):
    for c1 in range(1, 10):
        for c2 in range(1, 10):
            c_test = np.array([c0, c1, c2])
            D = c_test[:, None] - A
            x_bar = np.min(D, axis=0)
            R = (D == x_bar).astype(int)
            if np.all(np.sum(R, axis=1) == 1):
                print(f"Ketemu vektor c unik: {c_test}")
                print(R)
                break
        else:
            continue
        break
    else:
        continue
    break


Ketemu vektor c unik: [1 1 1]
[[0 0 1]
 [0 1 0]
 [1 0 0]]


---
### Apakah Ada Contoh Mutlak "Solusi Unik" di Latin Square?

Pertanyaan yang sangat kritis! Jika kita membicarakan matriks Latin Square $A$ yang dioperasikan dengan Max-Plus untuk dicari penyelesaian *unik*-nya (di mana Matriks $R$-nya benar-benar hanya punya **tepat satu angka 1 di tiap baris**), bentuknya seperti apa? 

Mari kita pakai matriks $A$ berorde 3 yang tadi dihasilkan:
$$
A = 
\begin{bmatrix}
1 & 2 & 3 \\
2 & 3 & 1 \\
3 & 1 & 2
\end{bmatrix}
$$

Apakah sistem persamaan $A \otimes x = c$ bisa punya *solusi unik mutlak*? **Bisa, TAPI target $c$-nya tidak boleh berasal dari perkalian Latin Square**. 
Misal, kita setting pelompat target secara paksa menjadi rata, $c = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}$.

Mari kita hitung Matriks Ketidaksesuaian $D$:
$$
D = c - A = 
\begin{bmatrix}
1-1 & 1-2 & 1-3 \\
1-2 & 1-3 & 1-1 \\
1-3 & 1-1 & 1-2
\end{bmatrix}
=
\begin{bmatrix}
0 & -1 & -2 \\
-1 & -2 & 0 \\
-2 & 0 & -1
\end{bmatrix}
$$

Subsolusi terbesarnya (minimum tiap kolom): $\bar{x} = \begin{bmatrix} -2, -2, -2 \end{bmatrix}^T$.
Sekarang kita buat matriks tereduksinya $R$ dengan mengganti nilai yang sama dengan $-2$ menjadi $1$:
$$
R = 
\begin{bmatrix}
0 & 0 & \mathbf{1} \\
0 & \mathbf{1} & 0 \\
\mathbf{1} & 0 & 0
\end{bmatrix}
$$

Sempurna! Di matriks $R$ ini, **tiap baris benar-benar hanya punya persis satu angka 1**. Ini adalah wujud mutlak dari **solusi unik**. Tak ada alternatif pilihan mana pun untuk vektor $x$ pelindungnya, solusinya **pasti** $x = [-2, -2, -2]^T$.

#### Mengapa Tidak Ada di Relasi Komutatif ($A \otimes B$)?
Kenapa contoh "solusi unik" tersebut tak akan terpanggil di saat program di atas sedang mencari pasangan komutatif?
Karena pada pencarian komutasi, ruas kanannya adalah $C = A \otimes B$. Nilai $C$ didapatkan dari pertambahan elemen-elemen Latin Square $\{1, 2, \dots, n\}$.
Masalahnya: penjumlahan himpunan $\{1 \dots n\}$ akan sering menabrak angka yang sama (Contoh: $1+3 = 4$, $2+2= 4$, nilainya kembar). 

Karena penjumlahan (lalu ditarik nilai Maksimum-nya) terus menerus menghasilkan angka yang **kembar**, nilai ketidaksesuaian ($D$) dan penandaan minimumnya ($R$) tak akan pernah mampu mengisolasi angka *satu biji per baris*. Ia akan selalu menghasilkan Matriks $R$ dengan banyak sekali angka $1$ di dalamnya.

**Kesimpulan:**
1. **Ya, matriks Latin Square punya solusi SPL yang super unik** $\to$ *Contohnya jika $c = [1, 1, 1]^T$, $R$-nya jadi matriks permutasi absolut.*
2. **Tapi, solusi unik ini sekadar "mitos pengandaian" (Teori Kontradiksi) jika dipakai mencari matriks komutatif** $\to$ Karena hasil silangan antar sesama matriks Latin tak akan pernah sanggup membuat angka 1 yang benar-benar tunggal akibat kelemahan unik penjumlahan himpunannya (*Pigeonhole collision*). Oleh sebab itu $A \neq B$ tak pernah butuh saling terisolasi.

---
### Eksperimen Solusi Mutlak (Unik) untuk $n=4$

Tentu saja ada! Konsepnya sama persis. Malahan, ada satu **trik rahasia** untuk secara mematikan memaksa *semua matriks Latin Square* berorde berapapun ($n=3, n=4, n=5$) memiliki solusi yang super unik.

Triknya: **Gunakan target yang bilangannya sama semua, misalnya $c = [1, 1, 1, 1]^T$.** 

Kenapa trik ini berhasil? 
Karena nilai angka maksimum di dalam matriks Latin Square orde 4 adalah angka `4`. Angka `4` ini sifat posisinya adalah *pasti muncul sekali di setiap baris dan kolom*. Jika target $c$ dipaksa kembar semua nilainya, maka nilai Ketidaksesuaian Minimum (subsolusi terbesar $\bar{x}$) selalu akan diserap mutlak oleh angka terbesar di matriks tersebut, yakni `4`. Karena angka `4` posisinya unik bak permutasi, maka Matriks $R$-nya otomatis langsung tereduksi menjadi Matriks Identitas Permutasi murni (tepat 1 nilai `1` di tiap baris).

Mari kita uji dengan salah satu elemen matriks orde 4 yang ada di memori program kita (`A_example`).

In [15]:
# Ambil salah satu matriks dari kode sebelumnya yg berorde 4
print("Matriks A Orde 4: \n", A_example)

# Buat target c yang nilainya sama rata (misal semuanya 1)
c_unique = np.array([1, 1, 1, 1])
print("\nTarget Vektor c: \n", c_unique)

# Hitung Matriks Ketidaksesuaian D
D = c_unique[:, None] - A_example
print("\nMatriks Ketidaksesuaian D: \n", D)

# Hitung Tereduksi R
x_bar = np.min(D, axis=0) # Angka minimum per kolom (karena 4 bilangan maksimumnya, nilainya akan selalu 1-4 = -3)
print("\nSubsolusi Terbesar x_bar:\n", x_bar)

R = (D == x_bar).astype(int)
print("\nMatriks R (Wow! Tepat satu angka 1 per baris):\n", R)

# Cek apakah setiap baris benar-benar unik
cek_unik = np.all(np.sum(R, axis=1) == 1)
print("\nApakah 100% memiliki solusi Unik? -> ", cek_unik)


Matriks A Orde 4: 
 [[4 3 2 1]
 [1 4 3 2]
 [2 1 4 3]
 [3 2 1 4]]

Target Vektor c: 
 [1 1 1 1]

Matriks Ketidaksesuaian D: 
 [[-3 -2 -1  0]
 [ 0 -3 -2 -1]
 [-1  0 -3 -2]
 [-2 -1  0 -3]]

Subsolusi Terbesar x_bar:
 [-3 -3 -3 -3]

Matriks R (Wow! Tepat satu angka 1 per baris):
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Apakah 100% memiliki solusi Unik? ->  True


### Bagaimana Mencarinya Tanpa Manipulasi $c$? (Koreksi Penting!)

Jika Anda bertanya: **"Apakah ada contoh matriks Latin Square di mana ia dikomutatifkan dengan matriks (baik dirinya sendiri maupun orang lain) yang memunculkan Solusi Unik satu biji per baris?"**

Jawabannya adalah **TIDAK ADA SAMA SEKALI** (Bisa dilihat hasil `Contoh A x A unik: None` di bawah). Bahkan ketika suatu matriks dikomutatifkan dengan dirinya sendiri pun ($A \otimes A$), ia **Gagal** menjadi unik.

Kenapa? Karena seperti yang dijelaskan di prinsip Sarang Merpati (*Pigeon-hole Principle*), hasil dari Max-Plus itu menjumlahkan elemen himpunan $\{1 \dots n\}$. Pertambahan tersebut pasti sering menabrak angka yang sama! Pada akhirnya, angka `1` di matriks tereduksi $R$ **akan selalu tumpang tindih (>1 angka 1)**.

Untuk contoh benarnya silakan lihat baris di blok kode di bawah ini di mana saya mem-print langsung wajah matriks $A$, $C = A \otimes A$, dan matriks ketidaksesuaian tereduksinya $R$.

In [16]:
import numpy as np

def test_unique_A_cross_A():
    for A in pool_n4:  # variable existing in the notebook
        C = max_plus_mult(A, A)
        unique_all = True
        for j in range(4):
            cj = C[:, j]
            D = cj[:, None] - A
            x_bar = np.min(D, axis=0)
            R = (D == x_bar).astype(int)
            if not np.all(np.sum(R, axis=1) == 1):
                unique_all = False
                break
        if unique_all:
            return A
    return None

contoh_AA_unik = test_unique_A_cross_A()
print("Contoh A x A unik:", contoh_AA_unik)


Contoh A x A unik: None


In [17]:
# Pembuktian bahwa A dikali A pun SOLUSINYA TETAP JAMAK (Tidak Unik)
A_test = pool_n4[0] # Ambil sembarang latin square Orde 4
print("Matriks A: \n", A_test)

C_self = max_plus_mult(A_test, A_test)
print("\nHasil C = A (x) A: \n", C_self)

# Ambil kolom ke-0 dari C sebagai target
c0_self = C_self[:, 0]
print(f"\nTarget c untuk kolom 0: {c0_self}")

D_self = c0_self[:, None] - A_test
x_bar_self = np.min(D_self, axis=0)
R_self = (D_self == x_bar_self).astype(int)

print("\nMatriks R untuk A (x) A (Kolom ke-0):")
print(R_self)
print("\nApakah solusi R ini unik (1 biji per baris)? ->", np.all(np.sum(R_self, axis=1) == 1))


Matriks A: 
 [[1 2 3 4]
 [2 1 4 3]
 [3 4 1 2]
 [4 3 2 1]]

Hasil C = A (x) A: 
 [[8. 7. 6. 5.]
 [7. 8. 5. 6.]
 [6. 5. 8. 7.]
 [5. 6. 7. 8.]]

Target c untuk kolom 0: [8. 7. 6. 5.]

Matriks R untuk A (x) A (Kolom ke-0):
[[0 0 0 1]
 [0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]

Apakah solusi R ini unik (1 biji per baris)? -> False


---
### Pembuktian Matematis Absolut: Mengapa Matriks $c = A \otimes B$ Sifatnya Selalu Jamak?

Jika Anda butuh "bukti mati" (*Rigorous Mathematical Proof*) mengapa matriks Latin Square yang ditabrakkan dengan sesamanya ($c = A \otimes B$) **tidak akan pernah** menghasilkan solusi tunggal, ini adalah pembuktian elegannya:

**Definisi:**
Misalkan $A$ dan $B$ adalah matriks *Latin Square* berorde $n \ge 2$. 
Kolom ke-$j$ dari $B$ dinotasikan dengan vektor $b$. Karena $B$ Latin Square, maka $b$ hanyalah permutasi dari bilangan $\{1, 2, \dots, n\}$.
Maka elemen target $c_i$ adalah hasil operasi baris $A$ dengan $b$: 
$$ c_i = \max_{k} (A_{ik} + b_k) $$

**Langkah 1: Menghitung Batas Bawah Total $c$**
Karena $b$ adalah himpunan $\{1 \dots n\}$, pasti ada tepat satu indeks, katakanlah $k^*$, di mana nilai $b_{k^*} = n$ (nilai maksimum).
Jika kita meninjau kolom $k^*$ tersebut untuk seluruh baris, kita tahu bahwa nilai maksimum haruslah lebih besar atau sama dengan kandidat manapun:
$$ c_i \ge A_{i, k^*} + b_{k^*} \implies c_i \ge A_{i, k^*} + n $$
Jika kita jumlahkan seluruh $c_i$ dari baris 1 sampai $n$:
$$ \sum_{i=1}^n c_i \ge \sum_{i=1}^n (A_{i, k^*} + n) $$
Karena kolom ke-$k^*$ dari $A$ (yaitu $A_{i, k^*}$) juga pastilah himpunan $\{1 \dots n\}$, jumlahnya adalah $\frac{n(n+1)}{2}$.
Maka, **Batas Bawah** jumlah total $c$ adalah:
$$ \sum_{i=1}^n c_i \ge \frac{n(n+1)}{2} + n^2 $$

**Langkah 2: Menghitung Maksimal jika Solusi Dianggap "Unik"**
Agar SPL memiliki **solusi unik**, Matriks Tereduksi $R$ harus bernilai unik di tiap baris dan kolom. Artinya tiap baris $i$ memiliki persis satu indeks $k(i)$ yang menghasilkan maksimum. 
Maka total $c$ hanyalah hasil pertambahan dari sel-sel diagonal permutasi $k(i)$ tersebut:
$$ \sum_{i=1}^n c_i = \sum_{i=1}^n A_{i, k(i)} + \sum_{i=1}^n b_{k(i)} $$
Karena unik, $b_{k(i)}$ akan mengunjungi semua kolom tepat sekali. Jumlah dari permutasi $\{1 \dots n\}$ tetap $\frac{n(n+1)}{2}$.
Sementara sel $A_{i, k(i)}$ paling banter maksimal bernilai $n$ di setiap kejadiannya. Maka maksimal $\sum A_{i, k(i)}$ adalah $n \times n = n^2$.
Maka, **Batas Atas** jika sistem tersebut unik adalah:
$$ \sum_{i=1}^n c_i \le \frac{n(n+1)}{2} + n^2 $$

**Langkah 3: KONTRADIKSI (The Aha! Moment)**
Perhatikan Batas Bawah dan Batas Atas. Satunya menyatakan $\ge$, satunya lagi $\le$ untuk nilai yang persis sama! Ini memaksa keadaan jatuh di titik potong kembar (ekuilibrium mutlak):
$$ \sum_{i=1}^n c_i = \frac{n(n+1)}{2} + n^2 $$
Namun, agar nilai totalnya tertahan maksimal, syaratnya adalah **seluruh nilai $c_i$ harus secara paksa dicapai oleh kolom $k^*$**.
Artinya untuk **setiap** baris $i$, nilai terbesarnya SELALU dimenangkan oleh elemen di kolom $k^*$ yang memiliki si angka $n$ raksasa tersebut!

**Karena seluruh baris dimenangkan oleh kolom $k^*$, maka dalam Matriks Tereduksi ($R$), angka 1 akan berderet vertikal memborong habis di kolom $k^*$.** 
$$ R = \left[ \begin{array}{ccc|c|cc} 
0 & \cdots & 0 & \mathbf{1} & 0 & \cdots \\
0 & \cdots & 0 & \mathbf{1} & 0 & \cdots \\
\vdots & \ddots & \vdots & \vdots & \vdots & \ddots \\
0 & \cdots & 0 & \mathbf{1} & 0 & \cdots 
\end{array} \right] $$

**Kesimpulan:**
Karena kolom $k^*$ memiliki penanda 1 di setiap baris, itu artinya **Kolom lain ($n-1$ kolom sisanya) bernilai KOSONG (0)**. 
Dalam ilmu Aljabar Linear maupun Max-Plus, parameter yang kolomnya 0 disebut **Variabel Bebas** (*Free Variables*). Ia tidak pernah dicegah oleh syarat persamaan apa pun dan bisa diturunkan jadi nilai berapa saja hingga $-\infty$. 

Karena ada Variabel Bebas (sebanyak $n-1$), maka Solusi SPL tersebut selamanya akan bernilai **TAK HINGGA / JAMAK**. 

***Terbukti secara mutlak (Q.E.D.) bahwa tidak satupun hasil perkalian Latin Square, ke sesama siapapun itu, yang tidak meninggalkan Celah Variabel Bebas Jamak.***