In [1]:
from typing import List, Iterable, Any
import itertools
import numpy as np

def generate_latin_squares(values: List[Any]) -> Iterable[list[list[Any]]]:
    n = len(values)
    vals = list(values)
    if len(set(vals)) != n:
        raise ValueError("All entries in `values` must be distinct.")
    row_used = [[False] * n for _ in range(n)]
    col_used = [[False] * n for _ in range(n)]
    square: list[list[Any]] = [[None] * n for _ in range(n)]

    def backtrack(cell: int):
        if cell == n * n:
            yield [row[:] for row in square]
            return
        r, c = divmod(cell, n)
        for k, v in enumerate(vals):
            if not row_used[r][k] and not col_used[c][k]:
                square[r][c] = v
                row_used[r][k] = True
                col_used[c][k] = True
                yield from backtrack(cell + 1)
                row_used[r][k] = False
                col_used[c][k] = False
                square[r][c] = None

    return backtrack(0)

vals = [1, 2, 3]
all_squares = list(generate_latin_squares(vals))
print("Banyak latin square:", len(all_squares))
for square in all_squares:
    for row in square:
        print(row)
    print()

Banyak latin square: 12
[1, 2, 3]
[2, 3, 1]
[3, 1, 2]

[1, 2, 3]
[3, 1, 2]
[2, 3, 1]

[1, 3, 2]
[2, 1, 3]
[3, 2, 1]

[1, 3, 2]
[3, 2, 1]
[2, 1, 3]

[2, 1, 3]
[1, 3, 2]
[3, 2, 1]

[2, 1, 3]
[3, 2, 1]
[1, 3, 2]

[2, 3, 1]
[1, 2, 3]
[3, 1, 2]

[2, 3, 1]
[3, 1, 2]
[1, 2, 3]

[3, 1, 2]
[1, 2, 3]
[2, 3, 1]

[3, 1, 2]
[2, 3, 1]
[1, 2, 3]

[3, 2, 1]
[1, 3, 2]
[2, 1, 3]

[3, 2, 1]
[2, 1, 3]
[1, 3, 2]



In [3]:
import numpy as np

def maxplus_mul(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    if A.ndim != 2 or B.ndim != 2:
        raise ValueError("A dan B harus matriks 2D.")
    m, n = A.shape
    n2, p = B.shape
    if n != n2:
        raise ValueError("Dimensi tidak cocok: kolom(A) harus = baris(B).")
    C = np.max(A[:, :, None] + B[None, :, :], axis=1)
    return C

# Contoh pemakaian
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]], dtype=float)
C = maxplus_mul(A, B)
print("A * B =")
print(C)

A * B =
[[10.  9.  8.]
 [13. 12. 11.]
 [16. 15. 14.]]


In [ ]:
import numpy as np
from typing import List, Tuple

def is_latin_square_matrix(M: np.ndarray) -> bool:
    """Cek apakah M adalah latin square (setiap baris & kolom permutasi dari himpunan yang sama)."""
    if M.ndim != 2:
        return False
    n, m = M.shape
    if n != m:
        return False
    symbols = np.unique(M)
    if symbols.size != n:
        return False
    symbol_set = set(symbols.tolist())
    for i in range(n):
        if set(M[i, :].tolist()) != symbol_set:
            return False
        if set(M[:, i].tolist()) != symbol_set:
            return False
    return True

def find_commutative_latin_pairs(matrices: List[np.ndarray]) -> List[Tuple[np.ndarray, np.ndarray]]:
    """Dari daftar matriks, cari semua pasangan (A,B) latin square dengan A≠B dan A⊗B = B⊗A (max-plus)."""
    result: List[Tuple[np.ndarray, np.ndarray]] = []
    n = len(matrices)
    for i in range(n):
        A = matrices[i]
        if not is_latin_square_matrix(A):
            continue
        for j in range(i + 1, n):
            B = matrices[j]
            if not is_latin_square_matrix(B):
                continue
            AB = maxplus_mul(A, B)
            BA = maxplus_mul(B, A)
            if np.array_equal(AB, BA):
                result.append((A, B))
    return result

# Contoh pemakaian dasar
values = [1, 2, 3]
latin_list = list(generate_latin_squares(values))
matrices = [np.array(L, dtype=float) for L in latin_list]
pairs = find_commutative_latin_pairs(matrices)
print("Jumlah pasangan komutatif:", len(pairs))
for idx, (A, B) in enumerate(pairs, start=1):
    print(f"Pasangan {idx}:")
    print("A =")
    print(A)
    print("B =")
    print(B)
    print("A * B (max-plus) =")
    print(maxplus_mul(A, B))
    print("-")

Jumlah pasangan komutatif: 15
